
title: Blog & Docs
author: Anusree Anilkumar
email: anilkumaranusree113@gmail.com
description: >-
  This site is my personal documentation, made public for anyone who might find my code scribbles useful! ❤️
baseurl: "/documentation" 
url: "https://Anusree6154s.github.io" 
repository: Anusree6154s/documentation
twitter_username: anu6154s
github_username: Anusree6154s
linkedin_username: anusreeanilkumar1
rss: rss

show_excerpts: true
theme: minima


plugins:
  - jekyll-feed

minima:
  date_format: "%d %b %Y"

header_pages:
  - _pages/home.md
  - _pages/about.md
  - _pages/table-of-contents.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs

include:
  - _pages
  - _layouts
  - content #https://chatgpt.com/share/6790bb9a-d5e4-8007-8bf7-790c1c43a7e4

disqus:
    shortname: anusree-anilkumar-blog

permalink: /:title/
