# ref: https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml
# https://opensource.com/article/21/11/jekyll-config-files
# https://nainagurung.medium.com/publish-github-pages-using-jekyll-369a8e2800b7


title: Your awesome title
author: Jorge Sanz
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Minima social links
twitter_username: jekyllrb
github_username: jekyll
linkedin_username: jsanz
rss: rss

# Build settings
theme: minima
# plugins:
# - jekyll-feed

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - import-modules/passport/passport-jwt/README.md
  - interview-study-materials/README.md
# Include from processing
# include:
#   - .sass-cache/

# Exclude from processing
# exclude:
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

