# Site settings
title: My Awesome Website
description: > 
  This is my personal website, built using Jekyll's minima theme and hosted on GitHub Pages.
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL

# Minima theme settings
theme: minima
paginate: 5 # Number of posts per page

# Author details (optional)
author:
  name: Your Name
  email: your-email@example.com

# Social links (optional)
social_links:
  twitter: your_twitter_handle
  github: your_github_username

# # Build settings
# markdown: kramdown
# plugins:
#   - jekyll-feed
