pages:
  - interview-study-materials
  - import-modules/passport
  - import-modules/tests

header_pages:
  - deployment
  - languages
  - takehome-guidelines


# Site settings
title: My Awesome Website
description: >
  This is my personal website, built using Jekyll's minima theme and hosted on GitHub Pages.


# Minima theme settings
theme: minima
paginate: 5 # Number of posts per page

# Author details (optional)
author: Anusree Anilkumar
name: nameeee
email: bla@gmail.com

github_username: jsanz
linkedin_username: jsanz

custom_message: "Welcome to my blog!"
