name: Update Table of Contents

on:
  push:
    branches:
      - main  # Run on pushes to the main branch; adjust if you have a different default branch

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate Table of Contents
        run: python generate_toc.py

      - name: Check for changes in README.md
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Automated update of Table of Contents"
            git push
          else
            echo "No changes in README.md"
          fi
